"$schema" = 'https://starship.rs/config-schema.json'

format = """$python$all $fill $cmd_duration$time
$character"""

add_newline = false

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[cmd_duration]
# min_time = 10
# show_milliseconds = true
format = "[$duration](bright-black)"

[fill]
symbol = ' '

[package]
format = " "

[time]
format = " [$time]($style)"
disabled = false

[python]
symbol = " "
format = '[(\($virtualenv\) )]($style)'

[git_branch]
symbol = " "
format = '[$branch]($style) '
style = 'bold green'

[git_metrics]
disabled = false
format = '(([ $added ]($added_style))([ $deleted ]($deleted_style)))'
only_nonzero_diffs = true
added_style = 'green'
deleted_style = 'red'

[line_break]
disabled = true
